In [1]:
import numpy as np
import pandas as pd

from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
np.__version__

'1.22.3'

# Getting the data

In [3]:
df = pd.read_csv('./data/data.csv')
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [4]:
# question 2: how many records are in the dataset?
number_of_rows = len(df)
print(f'there are {number_of_rows} rows in dataset')

there are 11914 rows in dataset


In [5]:
# question 3: who are the most popular car manufacturers (top-3) according to the dataset?
df.groupby('Make', as_index=False).agg({
    'Model': 'count'
}).sort_values(by='Model', ascending=False).head(3)

Make  Model
9    Chevrolet   1123
14        Ford    881
46  Volkswagen    809

In [6]:
# Question 4: what is number of unique Audi car models in the dataset?
answer = len(list(df[df['Make'] == 'Audi']['Model'].unique()))
print(f'answer = {answer}')

answer = 34


In [7]:
# Question 5: How many columns in the dataset have missing values?
columns_with_empty_values = []
for i in df.isna().sum():
    if i != 0:
        columns_with_empty_values.append(i)

answer = len(columns_with_empty_values)
print(f'answer = {answer}')

answer = 5


In [8]:
df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [9]:
# Question 6:
# find the median value of "Engine Cylinders":
before_fillna = df["Engine Cylinders"].median()

# calculate the most frequent value of the same "Engine Cylinders":
most_frequent_engine_cylinders = df.groupby("Engine Cylinders", as_index=False).agg({
    'Make': 'count'
}).sort_values(by='Make', ascending=False).reset_index(drop=True)['Engine Cylinders'][0]

print(f'the most frequent value of the same "Engine Cylinders" = {most_frequent_engine_cylinders}')

# Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(most_frequent_engine_cylinders)

# Now, calculate the median value of "Engine Cylinders" once again.
after_fillna = df["Engine Cylinders"].median()

# Has it changed?:
if before_fillna == after_fillna:
    print('No')
else:
    print("Yes")

the most frequent value of the same "Engine Cylinders" = 4.0
No


In [13]:
# Question 7:
number_of_rows = len(df[df['Make'] == 'Lotus'][[
    'Engine HP',
    'Engine Cylinders'
]].drop_duplicates())

if number_of_rows == 9:
    print(f'ok we have {number_of_rows} rows')
else:
    print('check again, number of rows is not 9')

X = df[df['Make'] == 'Lotus'][[
    'Engine HP',
    'Engine Cylinders'
]].drop_duplicates().reset_index(drop=True)

X = X.values
X


ok we have 9 rows


array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

# Matrix Equation for Linear Regression hand made model

5. Compute matrix-matrix multiplication between the transpose of X and X.

In [17]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [18]:
# create an array y with values:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [22]:
# multiply the inverse of XTX with the transpose of X:
XTX_inv_X = np.linalg.inv(XTX).dot(X.T)
XTX_inv_X

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [23]:
# and then multiply by y:
w = XTX_inv_X.dot(y)
w

array([  4.59494481, -63.56432501])

In [25]:
# what is the 1st value of element w?:
answer = w[0]
print(f'answer = {answer}')

answer = 4.594944810094551
